openapi: 3.0.0
info:
  title: Simulation Service
  description: The shared interface for the SciML and PyCIEMSS services. Differences in APIs should be contained to the `extra` argument.
  version: 0.1.0

paths:
  /simulate:
    post:
      summary: Perform a simulation
      operationId: simulateModel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                engine:
                  type: string
                  enum: [sciml, ciemss]
                  example: sciml
                model_config_id:
                  type: string
                  example: "ba8da8d4-047d-11ee-be56"
                timespan:
                  type: object
                  properties:
                    start:
                      type: integer
                      example: 0
                    end:
                      type: integer
                      example: 90
                  items:
                    type: integer
                extra:
                  description: optional extra system specific arguments for advanced use cases
                  type: object
              required:
                - engine
                - model_config_id
                - timespan
      responses:
        '200':
          description: Simulation created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_id:
                    type: string
                    example: fc5d80e4-0483-11ee-be56

  /calibrate:
    post:
      summary: Calibrate a model to data then simulate
      description: Calibrate a model and perform a "fitting" simulation over the time range of the calibration dataset and a simulation of a time range specified in `timespan` if `timespan` is specified. The SciML engine allows for calibration without additional simulation; in that case `timespan` is left off the payload.
      operationId: calibratesimulateModel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                engine:
                  type: string
                  enum: [sciml, ciemss]
                  example: sciml
                model_config_id:
                  type: string
                  example: "c1cd941a-047d-11ee-be56"
                dataset:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "cd339570-047d-11ee-be55"
                    filename:
                      type: string
                      example: "dataset.csv"
                    mappings:
                      type: object
                timespan:
                  type: object
                  properties:
                    start:
                      type: integer
                      example: 0
                    end:
                      type: integer
                      example: 90
                extra:
                  description: optional extra system specific arguments for advanced use cases
                  type: object
              required:
                - engine
                - model_config_id
                - dataset
      responses:
        '200':
          description: Calibration/simulation created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_id:
                    type: string
                    example: fc5d80e4-0483-11ee-be56
  
  /ensemble-simulate:
    post:
      summary: Perform an ensemble simulation
      operationId: createEnsemble
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                engine:
                  type: string
                  enum: [sciml, ciemss]           
                model_configs:
                  type: array
                  items:
                    type: object
                    properties:
                      model_config_id:
                        type: string
                      solution_mappings: 
                        type: object
                  example: 
                    - id: "ba8da8d4-047d-11ee-be56"
                      compartments: 
                        S: "Susceptible"
                        I: "Symptomatic+Asymptomatic"
                        R: "Healthy"
                      weight: 0.4
                    - id: "c1cd941a-047d-11ee-be56"
                      compartments: 
                        S: "S"
                        I: "I+D+A+R+T"
                        R: "H+E"
                      weight: 0.1
                    - id: "c4b9f88a-047d-11ee-be56"
                      compartments:
                        S: "S*10000"
                        I: "I*10000"
                        R: "R*10000"
                      weight: 0.5
                timespan:
                  type: object
                  properties:
                    start:
                      type: integer
                      example: 0
                    end:
                      type: integer
                      example: 90

                extra:
                  description: optional extra system specific arguments for advanced use cases
                  type: object                   
              required:
                - engine
                - model_config_id
                - timespan
      responses:
        '200':
          description: Ensemble created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_id:
                    type: string
                    example: fc5d80e4-0483-11ee-be56
  
  /ensemble-calibrate:
    post:
      summary: Calibrate an ensemble of models
      operationId: calibrateEnsemble
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                engine: 
                  type: string
                  enum: [sciml, ciemss]
                  example: sciml              
                model_configs:
                  type: array
                  items:
                    type: object
                    properties:
                      model_config_id:
                        type: string
                      solution_mappings: 
                        type: object
                  example: 
                    - id: "ba8da8d4-047d-11ee-be56"
                      compartments: 
                        S: "Susceptible"
                        I: "Symptomatic+Asymptomatic"
                        R: "Healthy"
                      weight: 0.4
                    - id: "c1cd941a-047d-11ee-be56"
                      compartments: 
                        S: "S"
                        I: "I+D+A+R+T"
                        R: "H+E"
                      weight: 0.1
                    - id: "c4b9f88a-047d-11ee-be56"
                      compartments:
                        S: "S*10000"
                        I: "I*10000"
                        R: "R*10000"
                      weight: 0.5
                dataset:
                  type: object
                  properties:
                    id: 
                      type: string
                      example: "cd339570-047d-11ee-be55"
                    filename:
                      type: string
                      example: "dataset.csv"
                    mappings:
                      type: object
                timespan:
                  type: object
                  properties:
                    start:
                      type: integer
                      example: 0
                    end:
                      type: integer
                      example: 90
                extra:
                  description: optional extra system specific arguments for advanced use cases
                  type: object
              required:
                - engine
                - model_config_ids
                - timespan
      responses:
        '200':
          description: Ensemble created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_id:
                    type: string
                    example: fc5d80e4-0483-11ee-be56

  /status/{simulation_id}:
    get:
      summary: Retrieve the status of a simulation
      operationId: getStatus
      parameters:
        - name: simulation_id
          in: path
          required: true
          schema:
            type: string
            example: fc5d80e4-0483-11ee-be56
      responses:
        '200':
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [queued, running, complete, error, failure]
